import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.css'
import Nav from '../components/nav'
export default function About() {
  return (
    <div >
      <Head>
      <title>Nick MacKenzie - Web Developer. Ontario, Canada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="wrapper">
    <div class="hero-image">
    <Nav></Nav>  
    <div class="about-text" className={styles.aboutText}>
          <br />
          <div class="intro" className={styles.intro}>
            <br />
            I am a meticulous, driven , and creative thinker who has worked
            professionally in both team and independent settings for the last
            ten years.<br /><br />
            I am a recent General Assembly graduate from the Software
            Engineering Immersive program. This has given me the knowledge to be
            proficient in JavaScript, HTML and CSS.<br /><br />
            I am searching for long term employment in an environment where I
            can continue to strengthen my skill set as a software developer.
          </div>
          <br /><br />
    </div>
  </div>
    </div>
    </div>
  )
}
