import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/nav'
export default function Contact() {
  return (
    <div>
      <Head>
      <title>Nick MacKenzie - Web Developer. Ontario, Canada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="wrapper">
    <div class="hero-image">
    <Nav></Nav>
    <div class="contact-form">
          <br />
          <h1>Contact Me</h1>
          <br />
          <form action="https://formspree.io/f/mzbrpgbl" method="POST">
            <div class="input-container">
              <i class="fal fa-address-card fa-2x icon"></i>

              <input
                class="input-field"
                type="text"
                placeholder="Name"
                name="name"
              />
            </div>
            <div class="input-container">
              <i class="fas fa-envelope-open-text fa-2x icon"></i>
              <input type="text" name="_replyto" placeholder="Your email" />
            </div>
            <div class="input-container">
              <i class="far fa-question-square fa-2x icon"></i>
              <input
                class="input-field"
                type="text"
                placeholder="Comments/Questions"
                name="comments"
              />
            </div>
            <br />
            <input id="btn" type="submit" />
          </form>
        </div>
    </div>
  </div>
    </div>
  )
}
